@startuml
autonumber
skinparam MinClassWidth 200
skinparam ParticipantPadding 50
skinparam sequence {
    ParticipantBorderColor brown
    ParticipantBackgroundColor khaki
}
box "Diagrama de Secuencia - Centro de Contacto ScotiaBank" #White
actor "Cliente"
participant "Sistema Call Center"
actor "Trabajador"
participant "Sistema Información"

"Cliente" [#0000FF]-> "Sistema Call Center" : Contacta al Call Center
"Sistema Call Center" [#0000FF]-> "Trabajador" : Direcciona llamada
"Trabajador" [#0000FF]-> "Sistema Información" : Recepciona Consulta y solicita documento
"Sistema Información" [#0000FF]-> "Trabajador": Devuelve Documento de consulta
"Trabajador" [#0000FF]-> "Cliente": Da respuesta a la consulta
"Trabajador" [#0000FF]-> "Sistema Información": Registra consulta y respuesta
"Cliente" [#0000FF]-> "Sistema Call Center": Finaliza llamada
"Sistema Call Center" [#0000FF]-> "Sistema Información": Guarda registro de llamada
end box

@endum
@enduml